import 'package:sqflite/sqflite.dart';
import '../../../core/database/database_helper.dart';
import '../domain/models/training.dart';
import '../domain/models/ai_training_plan.dart';

/// Handles SQLite database operations for the Training entity and its relations.
class TrainingRepository {
  /// Retrieves all training plans associated with a specific profile ID.
  /// Returns an empty list if no plans are found.
  Future<List<Training>> getTrainingsByProfile(int idProfile) async {
    final db = await DatabaseHelper.instance.database;

    final List<Map<String, dynamic>> maps = await db.query(
      'training',
      where: 'id_profile = ?',
      whereArgs: [idProfile],
    );

    return List.generate(maps.length, (i) {
      return Training.fromMap(maps[i]);
    });
  }

  /// Inserts a new basic training record into the local SQLite database.
  /// Returns the auto-generated ID of the newly inserted training.
  Future<int> createTraining(Training training) async {
    final db = await DatabaseHelper.instance.database;

    return await db.insert('training', training.toMap());
  }

  /// Saves a complete AI-generated training plan into the database using a transaction.
  /// This ensures that the base training, its routines (days), and all specific
  /// exercises are saved atomically. If any insertion fails, the entire operation rolls back.
  Future<int> saveFullAiTrainingPlan(
    Training baseTraining,
    AiTrainingPlan aiPlan,
  ) async {
    final db = await DatabaseHelper.instance.database;
    int newTrainingId = 0;

    // Use a transaction to guarantee data integrity across multiple tables
    await db.transaction((txn) async {
      // 1. Insert the main training record (the "header" of the routine)
      newTrainingId = await txn.insert(
        'training',
        baseTraining.toMap(),
        conflictAlgorithm: ConflictAlgorithm.replace,
      );

      // 2. Iterate through each day generated by the AI
      for (final day in aiPlan.days) {
        // Map the daily data.
        // IMPORTANT: Verify that 'training_day' matches your actual table name in DatabaseHelper.
        final dayData = {
          'id_training': newTrainingId,
          'day_number': day.day,
          'focus': day.focus,
        };

        final newDayId = await txn.insert('training_day', dayData);

        // 3. Iterate through all exercises for this specific day
        for (final exercise in day.exercises) {
          // Map the exercise data.
          // IMPORTANT: Verify that 'exercise' matches your actual table name in DatabaseHelper.
          final exerciseData = {
            'id_training_day': newDayId,
            'name': exercise.name,
            'sets': exercise.sets,
            'reps': exercise.reps,
            'rest_seconds': exercise.restSeconds,
            'description': exercise.description,
          };

          await txn.insert('exercise', exerciseData);
        }
      }
    });

    // Return the master ID so the UI can navigate to the detail screen
    return newTrainingId;
  }
}
