/// Represents the root structure of a diet plan generated by the AI.
class AiDietPlan {
  final List<DietDay> days;

  const AiDietPlan({required this.days});

  factory AiDietPlan.fromJson(Map<String, dynamic> json) {
    return AiDietPlan(
      days: (json['days'] as List<dynamic>?)
          ?.map((e) => DietDay.fromJson(e as Map<String, dynamic>))
          .toList() ??
          const [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'days': days.map((e) => e.toJson()).toList(),
    };
  }
}

/// Represents a single day in the diet plan with its caloric goal.
class DietDay {
  final int day;
  final int totalCalories;
  final List<DietMeal> meals;

  const DietDay({
    required this.day,
    required this.totalCalories,
    required this.meals,
  });

  factory DietDay.fromJson(Map<String, dynamic> json) {
    return DietDay(
      day: json['day'] as int? ?? 0,
      totalCalories: json['total_calories'] as int? ?? 0,
      meals: (json['meals'] as List<dynamic>?)
          ?.map((e) => DietMeal.fromJson(e as Map<String, dynamic>))
          .toList() ??
          const [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'day': day,
      'total_calories': totalCalories,
      'meals': meals.map((e) => e.toJson()).toList(),
    };
  }
}

/// Represents an individual meal within a [DietDay].
class DietMeal {
  final String type; // e.g., Breakfast
  final String name; // e.g., Oatmeal with Berries
  final String description;
  final int calories;

  const DietMeal({
    required this.type,
    required this.name,
    required this.description,
    required this.calories,
  });

  factory DietMeal.fromJson(Map<String, dynamic> json) {
    return DietMeal(
      type: json['type'] as String? ?? '',
      name: json['name'] as String? ?? '',
      description: json['description'] as String? ?? '',
      calories: json['calories'] as int? ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'name': name,
      'description': description,
      'calories': calories,
    };
  }
}