/// Represents an individual meal within a specific diet day.
class Meal {
  /// The category of the meal (e.g., "Breakfast", "Lunch", "Dinner", "Snack").
  final String type;

  /// The title of the meal (e.g., "Oatmeal with Berries").
  final String name;

  /// Detailed instructions or ingredients for the meal.
  final String description;

  /// Estimated caloric value of the meal.
  final int calories;

  const Meal({
    required this.type,
    required this.name,
    required this.description,
    required this.calories,
  });

  /// Safely constructs a [Meal] from a JSON map, providing fallback values
  /// to prevent parsing crashes if the AI omits a field.
  factory Meal.fromJson(Map<String, dynamic> json) {
    return Meal(
      type: json['type'] as String? ?? 'Unknown',
      name: json['name'] as String? ?? 'Unnamed Meal',
      description: json['description'] as String? ?? 'No description provided.',
      calories: json['calories'] as int? ?? 0,
    );
  }
}

/// Represents a single day of a generated diet plan, containing multiple [Meal]s.
class DietDay {
  /// The sequential day number (e.g., 1, 2, 3).
  final int dayNumber;

  /// A collection of meals scheduled for this specific day.
  final List<Meal> meals;

  /// The sum of calories for all meals in this day.
  final int totalCalories;

  const DietDay({
    required this.dayNumber,
    required this.meals,
    required this.totalCalories,
  });

  /// Safely parses a [DietDay] and its nested [Meal] list from JSON.
  factory DietDay.fromJson(Map<String, dynamic> json) {
    final mealList = json['meals'] as List<dynamic>? ?? [];

    return DietDay(
      dayNumber: json['day'] as int? ?? 1,
      totalCalories: json['total_calories'] as int? ?? 0,
      meals: mealList
          .map((m) => Meal.fromJson(m as Map<String, dynamic>))
          .toList(),
    );
  }
}

/// Represents the complete diet plan generated by the AI.
class DietPlan {
  /// The list of daily plans that make up the entire routine.
  final List<DietDay> days;

  const DietPlan({
    required this.days,
  });

  /// Safely parses the root [DietPlan] and its nested lists from the AI's JSON output.
  factory DietPlan.fromJson(Map<String, dynamic> json) {
    final dayList = json['days'] as List<dynamic>? ?? [];

    return DietPlan(
      days: dayList
          .map((d) => DietDay.fromJson(d as Map<String, dynamic>))
          .toList(),
    );
  }
}