/// Represents a dietary plan assigned to a specific user profile.
class Diet {
  /// Unique identifier for the diet plan (Auto-incremented by SQLite).
  final int? idDiet;

  /// Foreign key linking this diet to a specific user profile.
  final int idProfile;

  /// The descriptive name of the diet plan.
  final String name;

  /// The main goal of the diet (e.g., weight loss, muscle gain).
  final String objective;

  /// Any specific food allergies or intolerances.
  final String? allergies;

  /// Extra preferences or notes provided by the user.
  final String? additionalData;

  /// The raw JSON string generated by the AI. Null if generation failed or is pending.
  final String? generatedContent;

  const Diet({
    this.idDiet,
    required this.idProfile,
    required this.name,
    required this.objective,
    this.allergies,
    this.additionalData,
    this.generatedContent,
  });

  /// Converts a [Diet] instance into a Map for SQLite insertion.
  Map<String, dynamic> toMap() {
    return {
      'id_diet': idDiet,
      'id_profile': idProfile,
      'name': name,
      'objective': objective,
      'allergies': allergies,
      'additional_data': additionalData,
      'generated_content': generatedContent,
    };
  }

  /// Constructs a [Diet] instance from a SQLite Map object.
  factory Diet.fromMap(Map<String, dynamic> map) {
    return Diet(
      idDiet: map['id_diet'] as int?,
      idProfile: map['id_profile'] as int,
      name: map['name'] as String,
      objective: map['objective'] as String,
      allergies: map['allergies'] as String?,
      additionalData: map['additional_data'] as String?,
      generatedContent: map['generated_content'] as String?,
    );
  }
}