/// Represents the root structure of a training plan generated by the AI.
/// It contains a collection of individual training days.
class AiTrainingPlan {
  /// A list of daily workout routines.
  final List<TrainingDay> days;

  const AiTrainingPlan({required this.days});

  /// Factory constructor to securely parse the root JSON object.
  /// If the 'days' key is missing or malformed, it defaults to an empty list.
  factory AiTrainingPlan.fromJson(Map<String, dynamic> json) {
    return AiTrainingPlan(
      days:
          (json['days'] as List<dynamic>?)
              ?.map((e) => TrainingDay.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
    );
  }

  /// Converts the [AiTrainingPlan] instance back into a JSON-compatible map.
  Map<String, dynamic> toJson() {
    return {'days': days.map((e) => e.toJson()).toList()};
  }
}

/// Represents a single training day within the broader workout plan.
class TrainingDay {
  /// The specific day number in the sequence (e.g., 1, 2, 3).
  final int day;

  /// The primary muscle group or physiological focus for this specific day.
  final String focus;

  /// The list of exercises assigned to be performed on this day.
  final List<TrainingExercise> exercises;

  const TrainingDay({
    required this.day,
    required this.focus,
    required this.exercises,
  });

  /// Factory constructor to securely parse a daily routine from JSON.
  factory TrainingDay.fromJson(Map<String, dynamic> json) {
    return TrainingDay(
      day: json['day'] as int? ?? 0,
      focus: json['focus'] as String? ?? 'General Routine',
      exercises:
          (json['exercises'] as List<dynamic>?)
              ?.map((e) => TrainingExercise.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
    );
  }

  /// Converts the [TrainingDay] instance back into a JSON-compatible map.
  Map<String, dynamic> toJson() {
    return {
      'day': day,
      'focus': focus,
      'exercises': exercises.map((e) => e.toJson()).toList(),
    };
  }
}

/// Represents an individual exercise with specific performance metrics.
class TrainingExercise {
  /// The name of the exercise (e.g., "Barbell Bench Press").
  final String name;

  /// The total number of sets to be performed.
  final int sets;

  /// The target number of repetitions per set. Stored as a String to accommodate
  /// ranges (e.g., "8-10") or time-based metrics (e.g., "Failure").
  final String reps;

  /// The rest period required between sets, measured in seconds.
  final int restSeconds;

  /// Specific instructions, form cues, or tips for executing the exercise.
  final String description;

  const TrainingExercise({
    required this.name,
    required this.sets,
    required this.reps,
    required this.restSeconds,
    required this.description,
  });

  /// Factory constructor to securely parse an individual exercise from JSON.
  /// Includes robust type-checking and default fallbacks for AI hallucinations.
  factory TrainingExercise.fromJson(Map<String, dynamic> json) {
    return TrainingExercise(
      name: json['name'] as String? ?? 'Unknown Exercise',
      sets: json['sets'] as int? ?? 1,
      reps: json['reps']?.toString() ?? '1',
      restSeconds: json['rest_seconds'] as int? ?? 60,
      description: json['description'] as String? ?? '',
    );
  }

  /// Converts the [TrainingExercise] instance back into a JSON-compatible map.
  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'sets': sets,
      'reps': reps,
      'rest_seconds': restSeconds,
      'description': description,
    };
  }
}
