/// Represents a single exercise within a training session.
class Exercise {
  /// The name of the exercise (e.g., "Barbell Bench Press").
  final String name;

  /// The recommended number of sets.
  final int sets;

  /// The recommended repetition range or specific number (e.g., "8-12" or "10").
  final String reps;

  /// The rest time between sets in seconds.
  final int restSeconds;

  /// Brief instructions on execution or form focus.
  final String description;

  const Exercise({
    required this.name,
    required this.sets,
    required this.reps,
    required this.restSeconds,
    required this.description,
  });

  /// Safely constructs an [Exercise] from a JSON map with robust fallback values.
  factory Exercise.fromJson(Map<String, dynamic> json) {
    return Exercise(
      name: json['name'] as String? ?? 'Unnamed Exercise',
      sets: json['sets'] as int? ?? 3,
      reps: json['reps'] as String? ?? '10',
      restSeconds: json['rest_seconds'] as int? ?? 60,
      description: json['description'] as String? ?? '',
    );
  }
}

/// Represents a specific day in the training routine.
class TrainingDay {
  /// The sequential day number (e.g., 1, 2, 3).
  final int dayNumber;

  /// The primary muscle group or focus of the day (e.g., "Push", "Legs", "Cardio").
  final String focus;

  /// The list of exercises scheduled for this day.
  final List<Exercise> exercises;

  const TrainingDay({
    required this.dayNumber,
    required this.focus,
    required this.exercises,
  });

  /// Safely parses a [TrainingDay] and its nested [Exercise] list from JSON.
  factory TrainingDay.fromJson(Map<String, dynamic> json) {
    final exerciseList = json['exercises'] as List<dynamic>? ?? [];

    return TrainingDay(
      dayNumber: json['day'] as int? ?? 1,
      focus: json['focus'] as String? ?? 'General Training',
      exercises: exerciseList
          .map((e) => Exercise.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }
}

/// Represents the complete training routine generated by the AI.
class TrainingPlan {
  /// The list of daily plans that make up the entire routine.
  final List<TrainingDay> days;

  const TrainingPlan({required this.days});

  /// Safely parses the root [TrainingPlan] and its nested lists from the AI's JSON output.
  factory TrainingPlan.fromJson(Map<String, dynamic> json) {
    final dayList = json['days'] as List<dynamic>? ?? [];

    return TrainingPlan(
      days: dayList
          .map((d) => TrainingDay.fromJson(d as Map<String, dynamic>))
          .toList(),
    );
  }
}
